# Travis-CI build script for Thrill

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-4.9
      - g++-5
      - clang-3.6

sudo: false

matrix:
  include:
    - env: CMAKE_MODE="Debug"
    - env: CMAKE_MODE="Release"
  include:
    - env: CMAKE_CC="gcc-4.9" CMAKE_CXX="g++-4.9"
    - env: CMAKE_CC="gcc-5" CMAKE_CXX="g++-5"
    - env: CMAKE_CC="clang-3.6" CMAKE_CXX="clang++-3.6"

# env:
#   global:
#     # LeakSanitizer suppressions
#     - LSAN_OPTIONS=suppressions=$PWD/misc/leak_sanitizer.supp
#   matrix:
#     # Debug mode builds
#     - CMAKE_CC="gcc-4.9"   CMAKE_CXX="g++-4.9"     CMAKE_ARGS="" COMPILER_FLAGS="-fsanitize=address"
#     - CMAKE_CC="gcc-5"     CMAKE_CXX="g++-5"       CMAKE_ARGS="" COMPILER_FLAGS="-fsanitize=address" CMAKE_MODE="Debug"
#     - CMAKE_CC="clang-3.6" CMAKE_CXX="clang++-3.6" CMAKE_ARGS="" COMPILER_FLAGS="-fsanitize=address" CMAKE_MODE="Debug"
#     # Release mode builds
#     - CMAKE_CC="gcc-4.9"   CMAKE_CXX="g++-4.9"     CMAKE_ARGS="" COMPILER_FLAGS="-fsanitize=address" CMAKE_MODE="Release"
#     - CMAKE_CC="gcc-5"     CMAKE_CXX="g++-5"       CMAKE_ARGS="" COMPILER_FLAGS="-fsanitize=address" CMAKE_MODE="Release"
#     - CMAKE_CC="clang-3.6" CMAKE_CXX="clang++-3.6" CMAKE_ARGS="" COMPILER_FLAGS="-fsanitize=address" CMAKE_MODE="Release"

before_script:
  - mkdir build; cd build
  - cmake
      -DCMAKE_BUILD_TYPE="$CMAKE_MODE"
      -DCMAKE_C_COMPILER="$CMAKE_CC" -DCMAKE_CXX_COMPILER="$CMAKE_CXX"
      -DCMAKE_C_FLAGS="$COMPILER_FLAGS" -DCMAKE_CXX_FLAGS="$COMPILER_FLAGS"
      $CMAKE_ARGS ..

script:
  - make -j4 && ctest -V
