# Travis-CI build script for Thrill

language: cpp

sudo: false

matrix:
  include:
    # gcc 4.9 with AddressSanitizer, Debug & Release
    - env: CMAKE_CC="gcc-4.9" CMAKE_CXX="g++-4.9" BUILD_TYPE="Debug" COMPILER_FLAGS="-fsanitize=address"
      os: linux
      addons: &gcc49
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9

    - env: CMAKE_CC="gcc-4.9" CMAKE_CXX="g++-4.9" BUILD_TYPE="Release" COMPILER_FLAGS="-fsanitize=address"
      os: linux
      addons: *gcc49

    # gcc 5.x with AddressSanitizer, Debug & Release
    - env: CMAKE_CC="gcc-5" CMAKE_CXX="g++-5" BUILD_TYPE="Debug" COMPILER_FLAGS="-fsanitize=address"
      os: linux
      addons: &gcc5
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

    - env: CMAKE_CC="gcc-5" CMAKE_CXX="g++-5" BUILD_TYPE="Release" COMPILER_FLAGS="-fsanitize=address"
      os: linux
      addons: *gcc5

    # clang 3.6 with AddressSanitizer, Debug & Release
    - env: CMAKE_CC="clang-3.6" CMAKE_CXX="clang++-3.6" BUILD_TYPE="Debug" COMPILER_FLAGS="-fsanitize=address"
      os: linux
      addons: &clang36
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6

    - env: CMAKE_CC="clang-3.6" CMAKE_CXX="clang++-3.6" BUILD_TYPE="Release" COMPILER_FLAGS="-fsanitize=address"
      os: linux
      addons: *clang36

env:
  global:
    # LeakSanitizer suppressions
    - LSAN_OPTIONS=suppressions=$PWD/misc/leak_sanitizer.supp

before_script:
  - mkdir build; cd build
  - cmake
      -DCMAKE_BUILD_TYPE="$BUILD_TYPE"
      -DCMAKE_C_COMPILER="$CMAKE_CC" -DCMAKE_CXX_COMPILER="$CMAKE_CXX"
      -DCMAKE_C_FLAGS="$COMPILER_FLAGS" -DCMAKE_CXX_FLAGS="$COMPILER_FLAGS"
      $CMAKE_ARGS ..

script:
  - make -j4 && ctest -V
